@TmsApi_HostAddress = http://localhost:5115

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###1 1. Create a New enrollment
Post {{TmsApi_HostAddress}}/api/enrollments
Content-Type: application/json

{
    "studentId": "S-001",
    "courseId": "CS-101"
}
###1 1. Duplicate attempt for (Create a New enrollment)
Post {{TmsApi_HostAddress}}/api/enrollments
Content-Type: application/json

{
    "studentId": "S-001",
    "courseId": "CS-101"
}
